# Generated by Django 5.2.5 on 2025-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sent', models.TextField(verbose_name='תוכן שנשלח')),
                ('status', models.CharField(choices=[('SENT', 'נשלח'), ('DELIVERED', 'התקבל'), ('READ', 'נקרא'), ('REPLIED', 'השיב'), ('FAILED', 'נכשל')], default='SENT', max_length=20, verbose_name='סטטוס')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='תוכן התשובה')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'תקשורת',
                'verbose_name_plural': 'תקשורות',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='סוג')),
                ('identifier', models.CharField(help_text='כתובת מייל או מספר טלפון', max_length=255)),
                ('is_default', models.BooleanField(default=False, verbose_name='ברירת מחדל')),
            ],
            options={
                'verbose_name': 'שולח',
                'verbose_name_plural': 'שולחים',
            },
        ),
    ]
