# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('crm', '0002_initial'),
        ('marketing', '0001_initial'),
        ('smart_docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='communication',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_docs.documenttemplate'),
        ),
        migrations.AddField(
            model_name='sender',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.sender', verbose_name='נשלח מ-'),
        ),
    ]
