# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='תיאור פריט')),
            ],
            options={
                'verbose_name': 'פריט משלוח',
                'verbose_name_plural': 'פריטי משלוח',
            },
        ),
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם ספק השילוח')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='איש קשר')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('tracking_url_pattern', models.URLField(blank=True, help_text='תבנית URL למעקב (לדוגמה: https://www.fedex.com/fedextrack/?tracknumbers={tracking_number})', max_length=255, null=True, verbose_name='תבנית URL למעקב')),
            ],
            options={
                'verbose_name': 'ספק שילוח',
                'verbose_name_plural': 'ספקי שילוח',
            },
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='מספר אסמכתא להצעה')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='עלות')),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='ימי אספקה משוערים')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='תקף עד')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='התקבל בתאריך')),
                ('is_approved', models.BooleanField(default=False, verbose_name='אושר?')),
            ],
            options={
                'verbose_name': 'הצעת מחיר לשילוח',
                'verbose_name_plural': 'הצעות מחיר לשילוח',
            },
        ),
        migrations.CreateModel(
            name='ShippingQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='מספר אסמכתא לבקשה')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='תאריך בקשה')),
                ('due_date', models.DateField(verbose_name='תאריך יעד לקבלת הצעות')),
                ('status', models.CharField(choices=[('DRAFT', 'טיוטה'), ('SENT', 'נשלח לספקים'), ('RECEIVED', 'התקבלו הצעות'), ('APPROVED', 'אושר'), ('REJECTED', 'נדחה')], default='DRAFT', max_length=20, verbose_name='סטטוס בקשה')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
            ],
            options={
                'verbose_name': 'בקשת הצעת מחיר לשילוח',
                'verbose_name_plural': 'בקשות להצעות מחיר לשילוח',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='מספר אסמכתא למשלוח')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='מספר מעקב')),
                ('status', models.CharField(choices=[('DRAFT', 'טיוטה'), ('PENDING', 'ממתין לשילוח'), ('SHIPPED', 'נשלח'), ('IN_TRANSIT', 'במעבר'), ('DELIVERED', 'נמסר'), ('CANCELED', 'בוטל'), ('RETURNED', 'הוחזר')], default='DRAFT', max_length=20, verbose_name='סטטוס משלוח')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='תאריך שילוח')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='תאריך מסירה צפוי')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='תאריך מסירה בפועל')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='עלות משוערת')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='עלות בפועל')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.currency', verbose_name='מטבע עלות')),
            ],
            options={
                'verbose_name': 'משלוח',
                'verbose_name_plural': 'משלוחים',
                'ordering': ['-created_at'],
            },
        ),
    ]
