# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('logistics', '0001_initial'),
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        ('smart_docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packing_list_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_packing_lists', to='smart_docs.generateddocument', verbose_name='מסמך Packing List'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='projects.project', verbose_name='פרויקט קשור'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments_to_address', to='crm.shippingaddress', verbose_name='כתובת נמען'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments', to='crm.contact', verbose_name='איש קשר נמען'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shipments_from_address', to='crm.shippingaddress', verbose_name='כתובת שולח'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shipments', to='crm.contact', verbose_name='איש קשר שולח'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='מוצר'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='project_product_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='projects.projectproduct', verbose_name='פריט בפרויקט'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipment', verbose_name='משלוח'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.shippingprovider', verbose_name='ספק שילוח'),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.currency', verbose_name='מטבע'),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_quotes', to='logistics.shippingprovider', verbose_name='ספק שילוח'),
        ),
        migrations.AddField(
            model_name='shippingquoterequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipping_quotes', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי'),
        ),
        migrations.AddField(
            model_name='shippingquoterequest',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests_destination', to='crm.country', verbose_name='מדינת יעד'),
        ),
        migrations.AddField(
            model_name='shippingquoterequest',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests_origin', to='crm.country', verbose_name='מדינת מוצא'),
        ),
        migrations.AddField(
            model_name='shippingquoterequest',
            name='requested_providers',
            field=models.ManyToManyField(blank=True, related_name='quote_requests', to='logistics.shippingprovider', verbose_name='ספקים שהתבקשו'),
        ),
        migrations.AddField(
            model_name='shippingquoterequest',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_request', to='logistics.shipment', verbose_name='משלוח קשור'),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='logistics.shippingquoterequest', verbose_name='בקשת הצעת מחיר'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'product', 'project_product_line_item')},
        ),
        migrations.AlterUniqueTogether(
            name='shippingquote',
            unique_together={('request', 'provider')},
        ),
    ]
