# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='שם החברה')),
                ('slug', models.SlugField(help_text='מזהה קצר וייחודי לחברה (לדוגמה, עבור כתובות URL).', max_length=255, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='אזור זמן ברירת מחדל')),
                ('email_integration_marketing_enabled', models.BooleanField(default=False, verbose_name='אינטגרציית אימייל למודול שיווק פעילה?')),
                ('email_integration_service_enabled', models.BooleanField(default=False, verbose_name='אינטגרציית אימייל למודול שירות פעילה?')),
                ('default_file_storage_location', models.CharField(blank=True, help_text='לדוגמה: נתיב SharePoint או תיקייה ברשת. משמש כשמירת קבצים של המערכת כולה.', max_length=500, null=True, verbose_name='נתיב ברירת מחדל לשמירת קבצים')),
                ('backup_path', models.CharField(blank=True, help_text='נתיב לתיקייה ייעודית לשמירת גיבויי מערכת.', max_length=500, null=True, verbose_name='נתיב ספריית גיבוי')),
                ('settings', models.JSONField(blank=True, help_text='הגדרות גלובליות נוספות בפורמט JSON (לדוגמה: ימי עבודה, הגדרות חגים).', null=True, verbose_name='הגדרות נוספות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_currency', models.ForeignKey(blank=True, help_text='מטבע ברירת המחדל לדיווחים ותצוגה באפליקציה הראשית.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.currency', verbose_name='מטבע ראשי של החברה')),
            ],
            options={
                'verbose_name': 'חברה',
                'verbose_name_plural': 'חברות',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='מספר טלפון')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='תמונת פרופיל')),
                ('email_sync_enabled', models.BooleanField(default=False, verbose_name='סנכרון אימייל אישי פעיל?')),
                ('whatsapp_sync_enabled', models.BooleanField(default=False, verbose_name='סנכרון וואטסאפ אישי פעיל?')),
                ('whatsapp_numbers', models.JSONField(blank=True, help_text="רשימת מספרי וואטסאפ אישיים בפורמט JSON, לדוגמה: ['+972501234567', '+972529876543'].", null=True, verbose_name='מספרי וואטסאפ אישיים')),
                ('additional_permissions', models.ManyToManyField(blank=True, related_name='user_additional_permissions', to='auth.permission', verbose_name='הרשאות נוספות')),
                ('groups', models.ManyToManyField(blank=True, help_text='הקבוצות אליהן המשתמש משתייך. משתמש יקבל את כל ההרשאות המוקצות לכל אחת מהקבוצות שלו.', related_name='management_custom_user_groups', related_query_name='management_custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='הרשאות ספציפיות עבור משתמש זה.', related_name='management_custom_user_permissions', related_query_name='management_custom_user_permission', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='management.company', verbose_name='חברה')),
            ],
            options={
                'verbose_name': 'משתמש',
                'verbose_name_plural': 'משתמשים',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם המחלקה')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='management.company', verbose_name='חברה')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='מנהל מחלקה')),
            ],
            options={
                'verbose_name': 'מחלקה',
                'verbose_name_plural': 'מחלקות',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='management.department', verbose_name='מחלקה'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם התפקיד')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור התפקיד')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='הרשאות תפקיד')),
            ],
            options={
                'verbose_name': 'תפקיד',
                'verbose_name_plural': 'תפקידים',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הצוות')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='management.company', verbose_name='חברה')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='management.department', verbose_name='מחלקה')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='מנהל צוות')),
            ],
            options={
                'verbose_name': 'צוות',
                'verbose_name_plural': 'צוותים',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='management.team', verbose_name='צוות'),
        ),
    ]
