# Generated by Django 5.2.5 on 2025-08-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='backup_file',
            field=models.FileField(blank=True, help_text='העלה קובץ גיבוי בפורמט JSON כדי לייבא נתונים.', null=True, upload_to='backups/', verbose_name='קובץ גיבוי לייבוא'),
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='שער המרה')),
                ('date', models.DateField(verbose_name='תאריך השער')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='crm.currency', verbose_name='מטבע מקור')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='crm.currency', verbose_name='מטבע יעד')),
            ],
            options={
                'verbose_name': 'שער מטבע',
                'verbose_name_plural': 'שערי מטבעות',
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
