# Generated by Django 5.2.5 on 2025-08-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_company_backup_file_currencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(help_text='קובץ גיבוי של כל נתוני המערכת בפורמט JSON.', upload_to='system_backups/', verbose_name='קובץ גיבוי')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
            ],
            options={
                'verbose_name': 'גיבוי מערכת',
                'verbose_name_plural': 'גיבויי מערכת',
            },
        ),
    ]
