# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הלוח')),
            ],
            options={
                'verbose_name': 'לוח פרויקטים',
                'verbose_name_plural': 'לוחות פרויקטים',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם הפרויקט')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום צפוי')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='תקציב')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='עלות בפועל')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='גרסה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.account', verbose_name='לקוח')),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.opportunity', verbose_name='Opportunity מקושר')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='מנהל פרויקט')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='projects.project', verbose_name='פרויקט מקור')),
            ],
            options={
                'verbose_name': 'פרויקט',
                'verbose_name_plural': 'פרויקטים',
            },
        ),
        migrations.CreateModel(
            name='ProjectCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'הכנסה'), ('OUT', 'הוצאה')], max_length=3, verbose_name='כיוון')),
                ('name', models.CharField(max_length=255, verbose_name='תיאור')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='projects.project')),
            ],
            options={
                'verbose_name': 'תזרים מזומנים',
                'verbose_name_plural': 'תזרימי מזומנים',
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='תיאור פריט')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='מחיר מכירה ליחידה')),
                ('agent_percentage', models.FloatField(default=0.0, verbose_name='% עמלת סוכן')),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_projects', to='crm.account', verbose_name='סוכן')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='מוצר')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_products', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם השלב')),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.projectboard', verbose_name='לוח')),
            ],
            options={
                'verbose_name': 'שלב בפרויקט',
                'verbose_name_plural': 'שלבים בפרויקטים',
                'ordering': ['board', 'order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstage', verbose_name='שלב'),
        ),
    ]
