# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='finance.expensecategory')),
            ],
            options={
                'verbose_name': 'קטגוריית הוצאה',
                'verbose_name_plural': 'קטגוריות הוצאות',
            },
        ),
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('IN', 'הכנסה'), ('OUT', 'הוצאה')], max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('is_forecast', models.BooleanField(default=False, help_text='האם זו רשומת תחזית או תנועה בפועל')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expensecategory')),
            ],
        ),
    ]
