# Generated by Django 5.2.5 on 2025-08-26 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='שם כלל האוטומציה')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל?')),
                ('trigger_type', models.CharField(choices=[('ON_CREATE', 'ביצירת אובייקט'), ('ON_UPDATE', 'בעדכון אובייקט'), ('ON_DELETE', 'במחיקת אובייקט'), ('ON_FIELD_CHANGE', 'בשינוי שדה ספציפי'), ('ON_TIME', 'בזמן מתוזמן (לדוגמה: יום לפני תאריך יעד)'), ('ON_WEBHOOK', 'מאתחול חיצוני (Webhook)')], max_length=50, verbose_name='סוג טריגר')),
                ('trigger_field_name', models.CharField(blank=True, help_text="שם השדה אם הטריגר הוא 'בשינוי שדה ספציפי'", max_length=100, null=True, verbose_name='שם שדה טריגר')),
                ('conditions', models.JSONField(blank=True, help_text="הגדרות תנאים בפורמט JSON (לדוגמה: [{'field': 'amount', 'operator': 'gt', 'value': 1000}]).", null=True, verbose_name='תנאים')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='יוצר הכלל')),
                ('trigger_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules_triggered', to='contenttypes.contenttype', verbose_name='מודל טריגר')),
            ],
            options={
                'verbose_name': 'כלל אוטומציה',
                'verbose_name_plural': 'כללי אוטומציה',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר ביצוע')),
                ('action_type', models.CharField(choices=[('CREATE_OBJECT', 'צור אובייקט חדש'), ('UPDATE_OBJECT', 'עדכן אובייקט קיים'), ('SEND_EMAIL', 'שלח אימייל'), ('SEND_WHATSAPP', 'שלח הודעת WhatsApp'), ('CREATE_TASK', 'צור משימה'), ('SEND_ALERT', 'שלח התראה'), ('CALL_WEBHOOK', 'הפעל Webhook חיצוני')], max_length=50, verbose_name='סוג פעולה')),
                ('action_parameters', models.JSONField(blank=True, help_text="פרמטרים בפורמט JSON (לדוגמה: {'field': 'status', 'value': 'Won', 'recipients': ['owner']}).", null=True, verbose_name='פרמטרים לפעולה')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_actions_targeted', to='contenttypes.contenttype', verbose_name='מודל יעד לפעולה')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_automation.automationrule', verbose_name='כלל אוטומציה')),
            ],
            options={
                'verbose_name': 'פעולת אוטומציה',
                'verbose_name_plural': 'פעולות אוטומציה',
                'ordering': ['rule', 'order'],
            },
        ),
    ]
