# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הדף')),
                ('url_slug', models.SlugField(help_text='החלק של הכתובת שיופיע אחרי שם האתר', unique=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='תוכן (HTML)')),
                ('external_url', models.URLField(blank=True, help_text='השתמש בזה אם הדף קיים באתר חיצוני', null=True)),
                ('lead_recipient', models.ForeignKey(blank=True, help_text='המשתמש שיקבל את הלידים מדף זה', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'דף נחיתה',
                'verbose_name_plural': 'דפי נחיתה',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם הקמפיין')),
                ('status', models.CharField(choices=[('PLANNED', 'מתוכנן'), ('ACTIVE', 'פעיל'), ('COMPLETED', 'הסתיים'), ('CANCELLED', 'בוטל')], default='PLANNED', max_length=20, verbose_name='סטטוס')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='תקציב')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(verbose_name='תאריך סיום')),
                ('content', models.TextField(blank=True, null=True, verbose_name='תוכן הקמפיין')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='תזמון שליחה')),
                ('throttle_rate', models.PositiveIntegerField(default=3, verbose_name='כמות הודעות')),
                ('throttle_period', models.CharField(choices=[('MIN', 'דקה'), ('HOUR', 'שעה')], default='MIN', max_length=10, verbose_name='בכל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='campaigns', to='crm.contact', verbose_name='אנשי קשר משויכים')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='אחראי')),
                ('landing_pages', models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.landingpage', verbose_name='דפי נחיתה משויכים')),
            ],
            options={
                'verbose_name': 'קמפיין',
                'verbose_name_plural': 'קמפיינים',
            },
        ),
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NEW', 'חדש'), ('CONTACTED', 'נוצר קשר'), ('QUALIFIED', 'כשיר'), ('UNQUALIFIED', 'לא כשיר')], default='NEW', max_length=20, verbose_name='סטטוס')),
                ('opt_out_email', models.BooleanField(default=False)),
                ('opt_out_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing.campaign', verbose_name='קמפיין')),
                ('converted_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_lead', to='crm.contact')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.landingpage', verbose_name='מקור הליד (דף נחיתה)')),
            ],
            options={
                'verbose_name': 'ליד שיווקי',
                'verbose_name_plural': 'לידים שיווקיים',
            },
        ),
    ]
