# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם התבנית')),
                ('subject', models.CharField(max_length=255, verbose_name='נושא')),
                ('body', models.TextField(help_text='HTML body with placeholders like {{opportunity.name}} or {{project.name}}')),
            ],
            options={
                'verbose_name': 'תבנית מסמך',
                'verbose_name_plural': 'תבניות מסמכים',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'טיוטה'), ('SENT', 'נשלח'), ('VIEWED', 'נצפה'), ('SIGNED', 'נחתם')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketing.campaign')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart_docs.documenttemplate')),
            ],
            options={
                'verbose_name': 'מסמך שנוצר',
                'verbose_name_plural': 'מסמכים שנוצרו',
            },
        ),
        migrations.CreateModel(
            name='DocumentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='סוג אירוע')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='זמן אירוע')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='smart_docs.generateddocument')),
            ],
            options={
                'verbose_name': 'מעקב מסמך',
                'verbose_name_plural': 'מעקבי מסמכים',
                'ordering': ['-timestamp'],
            },
        ),
    ]
