# Generated by Django 5.2.5 on 2025-08-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('smart_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logistics.shipment'),
        ),
    ]
