# Generated by Django 5.2.5 on 2025-08-26 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_docs', '0002_generateddocument_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(blank=True, help_text='העלה קובץ Word (docx) ליצירת תבנית.', null=True, upload_to='document_templates/word/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='קובץ תבנית Word'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='body',
            field=models.TextField(blank=True, help_text='HTML body with placeholders like {{opportunity.name}} or {{project.name}}', null=True),
        ),
    ]
