# Generated by Django 5.2.5 on 2025-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_docs', '0003_documenttemplate_file_alter_documenttemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('SALES', 'מכירות'), ('PROJECTS', 'פרויקטים'), ('LOGISTICS', 'לוגיסטיקה'), ('MARKETING', 'שיווק'), ('GENERAL', 'כללי')], default='GENERAL', max_length=20, verbose_name='קטגוריה'),
        ),
    ]
