# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם ה-Dashboard')),
                ('is_public', models.BooleanField(default=False, verbose_name='ציבורי?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_owned', to=settings.AUTH_USER_MODEL, verbose_name='בעלים')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם הדוח')),
                ('report_type', models.CharField(choices=[('OPPORTUNITIES_BY_STAGE', 'הזדמנויות לפי שלב'), ('SALES_BY_MONTH', 'מכירות לפי חודש'), ('PROJECTS_PROGRESS', 'התקדמות פרויקטים'), ('FINANCIAL_FORECAST', 'תחזית פיננסית'), ('CUSTOM', 'מותאם אישית')], default='CUSTOM', max_length=50, verbose_name='סוג דוח')),
                ('settings', models.JSONField(blank=True, help_text="הגדרות דוח בפורמט JSON (לדוגמה: {'filters': {'owner_id': 1}, 'group_by': 'stage'}).", null=True, verbose_name='הגדרות דוח')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.dashboard', verbose_name='Dashboard קשור')),
            ],
            options={
                'verbose_name': 'דוח',
                'verbose_name_plural': 'דוחות',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="שם הווידג'ט")),
                ('widget_type', models.CharField(choices=[('BAR_CHART', 'תרשים עמודות'), ('PIE_CHART', 'תרשים עוגה'), ('LINE_CHART', 'תרשים קו'), ('TABLE', 'טבלה'), ('GAUGE', 'מד התקדמות'), ('KPI_CARD', 'כרטיס KPI')], default='KPI_CARD', max_length=50, verbose_name="סוג ווידג'ט")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('display_settings', models.JSONField(blank=True, help_text="הגדרות תצוגה בפורמט JSON (לדוגמה: {'color': '#FF0000', 'width': '300px'}).", null=True, verbose_name='הגדרות תצוגה')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reporting.report', verbose_name='דוח קשור')),
            ],
            options={
                'verbose_name': "ווידג'ט",
                'verbose_name_plural': "ווידג'טים",
                'ordering': ['report', 'order'],
            },
        ),
    ]
