# Generated by Django 5.2.5 on 2025-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_settings', models.JSONField(blank=True, help_text="הגדרות מיקום וגודל בפורמט JSON (לדוגמה: {'x': 0, 'y': 0, 'width': 6, 'height': 4}).", null=True, verbose_name='הגדרות מיקום וגודל')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל?')),
            ],
            options={
                'verbose_name': "ווידג'ט בדשבורד",
                'verbose_name_plural': "ווידג'טים בדשבורדים",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='הדשבורד שלי', max_length=100, verbose_name='שם הדשבורד')),
                ('layout_settings', models.JSONField(blank=True, help_text="הגדרות פריסת ווידג'טים בפורמט JSON (לדוגמה: {'grid': 'responsive', 'columns': 12}).", null=True, verbose_name='הגדרות פריסה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'דשבורד משתמש',
                'verbose_name_plural': 'דשבורדים למשתמשים',
            },
        ),
    ]
