# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_hub', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='reporting_widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_instances', to='reporting.widget', verbose_name="ווידג'ט דיווח"),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL, verbose_name='משתמש'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='business_hub.userdashboard', verbose_name='דשבורד'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('dashboard', 'reporting_widget')},
        ),
    ]
