# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('projects', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם החוזה')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(verbose_name='תאריך סיום')),
                ('total_hours_allocated', models.FloatField(default=0.0, verbose_name='בנק שעות')),
                ('total_budget_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='תקציב כספי')),
                ('hours_used', models.FloatField(default=0.0, verbose_name='שעות שנוצלו (מחושב)')),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='תקציב שנוצל (מחושב)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='crm.account', verbose_name='לקוח')),
            ],
            options={
                'verbose_name': 'חוזה שירות',
                'verbose_name_plural': 'חוזי שירות',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='נושא הפנייה')),
                ('status', models.CharField(choices=[('OPEN', 'פתוח'), ('IN_PROGRESS', 'בטיפול'), ('CLOSED', 'סגור'), ('ON_HOLD', 'בהמתנה')], default='OPEN', max_length=20, verbose_name='סטטוס')),
                ('priority', models.CharField(choices=[('LOW', 'נמוכה'), ('MEDIUM', 'בינונית'), ('HIGH', 'גבוהה'), ('URGENT', 'דחופה')], default='MEDIUM', max_length=20, verbose_name='עדיפות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.account', verbose_name='לקוח')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.contact', verbose_name='איש קשר')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='אחראי')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='projects.project', verbose_name='פרויקט')),
                ('related_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='quotations.quotation', verbose_name='הצעת מחיר לשירות')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='service.servicecontract', verbose_name='חוזה שירות')),
            ],
            options={
                'verbose_name': 'פניית שירות (טיקט)',
                'verbose_name_plural': 'פניות שירות (טיקטים)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='תוכן העדכון')),
                ('time_spent_hours', models.FloatField(default=0.0, verbose_name='זמן שהושקע (בשעות)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service.ticket', verbose_name='פנייה')),
            ],
            options={
                'verbose_name': 'עדכון לפנייה',
                'verbose_name_plural': 'עדכונים לפנייה',
                'ordering': ['-created_at'],
            },
        ),
    ]
