# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הקטגוריה')),
            ],
            options={
                'verbose_name': 'קטגוריית משימה',
                'verbose_name_plural': 'קטגוריות משימות',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('due_date', models.DateTimeField(verbose_name='תאריך יעד')),
                ('status', models.CharField(choices=[('NEW', 'חדשה'), ('IN_PROGRESS', 'בתהליך'), ('COMPLETED', 'הושלמה')], default='NEW', max_length=20, verbose_name='סטטוס')),
                ('priority', models.CharField(choices=[('LOW', 'נמוכה'), ('MEDIUM', 'בינונית'), ('HIGH', 'גבוהה')], default='MEDIUM', max_length=20, verbose_name='עדיפות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.account', verbose_name='לקוח')),
                ('assignees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='אחראים')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact', verbose_name='איש קשר')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sales.opportunity', verbose_name='Opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='פרויקט')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='solutions.solution', verbose_name='פתרון מקושר')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskcategory', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'משימה',
                'verbose_name_plural': 'משימות',
                'ordering': ['due_date'],
            },
        ),
    ]
