# Generated by Django 5.2.5 on 2025-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('is_customer', models.BooleanField(default=False, verbose_name='לקוח')),
                ('is_vendor', models.BooleanField(default=False, verbose_name='ספק')),
                ('is_represented_vendor', models.BooleanField(default=False, verbose_name='ספק מיוצג')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'סוג לקוח',
                'verbose_name_plural': 'סוגי לקוחות',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='WhatsApp Number')),
                ('skype_id', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='איש קשר ראשי')),
                ('is_billing', models.BooleanField(default=False, verbose_name='איש קשר לחשבוניות')),
                ('is_shipping', models.BooleanField(default=False, verbose_name='איש קשר למשלוחים')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('regulation_status', models.CharField(choices=[('STANDARD', 'רגיל'), ('EXEMPT', 'פטור מרישיון שיווק'), ('FORBIDDEN', 'אסור לשיווק ומסחר'), ('SPECIAL', 'תנאים מיוחדים')], default='STANDARD', max_length=20, verbose_name='סטטוס רגולטורי (אפ"י)')),
                ('regulation_notes', models.TextField(blank=True, null=True, verbose_name='הערות רגולציה')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='שם המטבע')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='קוד (e.g., USD)')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='סמל')),
            ],
            options={
                'verbose_name': 'מטבע',
                'verbose_name_plural': 'מטבעות',
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incoterm',
                'verbose_name_plural': 'Incoterms',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'תנאי תשלום',
                'verbose_name_plural': 'תנאי תשלום',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
