# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='crm.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clienttype', verbose_name='סוג לקוח'),
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='business_countries',
            field=models.ManyToManyField(blank=True, related_name='accounts_operating_in', to='crm.country', verbose_name='מדינות פעילות עסקית'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(blank=True, help_text='המדינה הראשית של החברה', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.country', verbose_name='מדינה'),
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.industry', verbose_name='תעשייה'),
        ),
        migrations.AddField(
            model_name='account',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.leadsource', verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='crm.account'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.country'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses_contact', to='crm.contact'),
        ),
    ]
