# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הקטגוריה')),
            ],
            options={
                'verbose_name': 'קטגוריית פתרונות',
                'verbose_name_plural': 'קטגוריות פתרונות',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='שם הפתרון')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='מחיר כולל לחבילה, אם רלוונטי', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='solutions', to='products.product', verbose_name='מוצרים בפתרון')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.solutioncategory', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'פתרון',
                'verbose_name_plural': 'פתרונות',
            },
        ),
    ]
