# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='תאריך ושעת פעולה')),
                ('action', models.CharField(choices=[('CREATE', 'יצירה'), ('UPDATE', 'עדכון'), ('DELETE', 'מחיקה'), ('LOGIN', 'התחברות'), ('LOGOUT', 'התנתקות'), ('OTHER', 'אחר')], max_length=10, verbose_name='פעולה')),
                ('description', models.TextField(blank=True, help_text='תיאור קריא של הפעולה שבוצעה.', verbose_name='תיאור הפעולה')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('change_data', models.JSONField(blank=True, help_text="נתוני השינוי בפורמט JSON (לדוגמה, {'field': {'old': 'val', 'new': 'val'}})", null=True)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='מודול אפליקציה')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם מודל')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='מפתח סשן')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'לוג ביקורת',
                'verbose_name_plural': 'לוגי ביקורת',
                'ordering': ['-timestamp'],
            },
        ),
    ]
