# Generated by Django 5.2.5 on 2025-08-28 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הסוכן')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור הסוכן')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל?')),
                ('llm_settings', models.JSONField(blank=True, help_text="הגדרות עבור מודל השפה (לדוגמה: {'temperature': 0.7, 'model': 'gpt-4'}).", null=True, verbose_name='הגדרות LLM')),
                ('system_prompt', models.TextField(blank=True, help_text="הוראות למודל השפה (לדוגמה: 'אתה עוזר מכירות חכם...').", null=True, verbose_name='הנחיית מערכת (System Prompt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to=settings.AUTH_USER_MODEL, verbose_name='יוצר הסוכן')),
            ],
            options={
                'verbose_name': 'סוכן AI',
                'verbose_name_plural': 'סוכני AI',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הכלי (לדוגמה: create_opportunity)')),
                ('description', models.TextField(verbose_name='תיאור הכלי (למודל השפה)')),
                ('parameters', models.JSONField(blank=True, help_text="הגדרת הפרמטרים של הכלי בפורמט JSON Schema (לדוגמה: {'type': 'object', 'properties': {'name': {'type': 'string'}}}).", null=True, verbose_name='פרמטרים (JSON Schema)')),
                ('function_name', models.CharField(max_length=255, verbose_name='שם פונקציה בקוד')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='ai_agent.aiagent', verbose_name='סוכן AI')),
            ],
            options={
                'verbose_name': 'כלי AI',
                'verbose_name_plural': 'כלי AI',
                'ordering': ['name'],
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
