# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='סוג רישיון')),
            ],
            options={
                'verbose_name': 'סוג רישיון',
                'verbose_name_plural': 'סוגי רישיונות',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='מספר רישיון')),
                ('issue_date', models.DateField(verbose_name='תאריך הנפקה')),
                ('expiry_date', models.DateField(verbose_name='תאריך תפוגה')),
                ('file', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='קובץ רישיון')),
                ('accounts', models.ManyToManyField(related_name='licenses', to='crm.account', verbose_name='שותפים עסקיים (לקוח/ספק)')),
                ('issuing_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.country', verbose_name='מדינה מנפיקה')),
                ('opportunities', models.ManyToManyField(blank=True, related_name='licenses', to='sales.opportunity')),
                ('products', models.ManyToManyField(blank=True, related_name='licenses', to='products.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='projects.project')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulation.licensetype', verbose_name='סוג רישיון')),
            ],
            options={
                'verbose_name': 'רישיון',
                'verbose_name_plural': 'רישיונות',
            },
        ),
        migrations.CreateModel(
            name='DECARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_reference_number', models.CharField(max_length=50, verbose_name='מספר סימוכין (שלנו)')),
                ('deca_tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='מספר מעקב אפ"י')),
                ('request_type', models.CharField(max_length=100, verbose_name='סוג בקשה')),
                ('description', models.TextField(verbose_name='תיאור הבקשה')),
                ('status', models.CharField(choices=[('SUBMITTED', 'הוגשה'), ('IN_REVIEW', 'בטיפול'), ('APPROVED', 'אושרה'), ('REJECTED', 'נדחתה')], default='SUBMITTED', max_length=20)),
                ('submission_date', models.DateField(verbose_name='תאריך הגשה')),
                ('last_update_date', models.DateField(blank=True, null=True, verbose_name='תאריך עדכון אחרון')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.country')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('resulting_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deca_requests', to='regulation.license')),
            ],
            options={
                'verbose_name': 'בקשת אפ"י',
                'verbose_name_plural': 'בקשות לאפ"י',
            },
        ),
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('UPDATE', 'עדכון מדינות'), ('TRAINING', 'תיעוד הדרכה')], max_length=20, verbose_name='סוג מסמך')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('file', models.FileField(upload_to='regulation_docs/', verbose_name='קובץ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'מסמך רגולציה',
                'verbose_name_plural': 'מסמכי רגולציה',
            },
        ),
    ]
