# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם הצעת המחיר / מק"ט')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סכום ביניים (מחושב)')),
                ('vat_percentage', models.FloatField(default=17.0, verbose_name='אחוז מע"מ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סכום מע"מ (מחושב)')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סה"כ כולל מע"מ (מחושב)')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='גרסה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.incoterm', verbose_name='תנאי שילוח')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sales.opportunity', verbose_name='Opportunity')),
                ('parent_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='quotations.quotation')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.paymentterm', verbose_name='תנאי תשלום')),
            ],
            options={
                'verbose_name': 'הצעת מחיר',
                'verbose_name_plural': 'הצעות מחיר',
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='תיאור פריט')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='מחיר מכירה ליחידה')),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סך הכל שורה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='מוצר')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_products', to='quotations.quotation')),
            ],
        ),
    ]
