# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.core.validators
import django.db.models.deletion
import smart_selects.db_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם סוג היעד')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_financial', models.BooleanField(default=False, verbose_name='יעד כספי?')),
                ('is_activity_based', models.BooleanField(default=False, verbose_name='מבוסס פעילות?')),
                ('related_field', models.CharField(blank=True, help_text="שדה במודל קשור לחישוב התקדמות (לדוגמה: 'amount' ב-Opportunity)", max_length=100, null=True, verbose_name='שדה קשור')),
                ('related_model', models.CharField(blank=True, help_text="שם המודל הקשור (לדוגמה: 'Opportunity', 'Activity')", max_length=100, null=True, verbose_name='מודל קשור')),
            ],
            options={
                'verbose_name': 'סוג יעד',
                'verbose_name_plural': 'סוגי יעדים',
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='סיבת הפסד')),
            ],
            options={
                'verbose_name': 'סיבת הפסד',
                'verbose_name_plural': 'סיבות הפסד',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם ה-Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם היעד')),
                ('level', models.CharField(choices=[('INDIVIDUAL', 'אישי'), ('TEAM', 'צוותי'), ('COMPANY', 'חברתי')], default='INDIVIDUAL', max_length=20, verbose_name='רמת יעד')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ערך יעד')),
                ('frequency', models.CharField(choices=[('DAILY', 'יומי'), ('WEEKLY', 'שבועי'), ('MONTHLY', 'חודשי'), ('QUARTERLY', 'רבעוני'), ('YEARLY', 'שנתי')], default='MONTHLY', max_length=10, verbose_name='תדירות')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(verbose_name='תאריך סיום')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_owned', to=settings.AUTH_USER_MODEL, verbose_name='בעל יעד (משתמש)')),
                ('goal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='sales.goaltype', verbose_name='סוג יעד')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.pipeline', verbose_name='Pipeline קשור')),
            ],
            options={
                'verbose_name': 'יעד',
                'verbose_name_plural': 'יעדים',
                'unique_together': {('name', 'goal_type', 'owner', 'pipeline', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם ה-Opportunity')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סכום (מתעדכן אוטומטית)')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='עלויות (מתעדכן אוטומטית)')),
                ('total_agent_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סה"כ עמלת סוכן (מחושב)')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='רווח כולל (מחושב)')),
                ('profit_percentage', models.FloatField(default=0.0, verbose_name='% רווחיות (מחושב)')),
                ('vat_percentage', models.FloatField(default=17.0, verbose_name='אחוז מע"מ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סכום מע"מ (מחושב)')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סה"כ כולל מע"מ (מחושב)')),
                ('close_date', models.DateField(verbose_name='תאריך סגירה צפוי')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.account', verbose_name='לקוח')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.currency', verbose_name='מטבע עסקה')),
                ('incoterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.incoterm', verbose_name='תנאי שילוח')),
                ('lost_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.lostreason', verbose_name='סיבת הפסד')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='אחראי')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.paymentterm', verbose_name='תנאי תשלום כלליים')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='תיאור פריט')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='מחיר מכירה ליחידה')),
                ('supplier_pn', models.CharField(blank=True, max_length=100, null=True, verbose_name='מק"ט ספק')),
                ('agent_percentage', models.FloatField(default=0.0, verbose_name='% עמלת סוכן')),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סך הכל שורה')),
                ('line_profit_before_agent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='רווח לפני סוכן')),
                ('line_profit_after_agent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='רווח אחרי סוכן')),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deals', to='crm.account', verbose_name='סוכן')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='מוצר')),
            ],
            options={
                'unique_together': {('opportunity', 'product')},
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.ManyToManyField(blank=True, through='sales.OpportunityProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='תיאור אבן דרך')),
                ('percentage', models.FloatField(default=0.0, verbose_name='אחוז תשלום')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='סכום (כולל מע"מ, מחושב)')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='sales.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.pipeline', verbose_name='סוג Opportunity / Pipeline'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם השלב')),
                ('order', models.PositiveIntegerField(default=0)),
                ('win_probability', models.FloatField(default=0.0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sales.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'שלב',
                'verbose_name_plural': 'שלבים',
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'name')},
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='opportunity_pipeline', chained_model_field='pipeline', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.stage', verbose_name='שלב'),
        ),
        migrations.CreateModel(
            name='GoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ערך יעד משנה')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='הושג?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goal_targets', to=settings.AUTH_USER_MODEL, verbose_name='משויך ל')),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_targets', to='sales.goal', verbose_name='יעד אב')),
            ],
            options={
                'verbose_name': 'יעד משנה',
                'verbose_name_plural': 'יעדי משנה',
                'unique_together': {('parent_goal', 'assignee')},
            },
        ),
    ]
