# Generated by Django 5.2.5 on 2025-08-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='שם המוצר')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='מק"ט')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='מחיר קנייה')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='מטבע')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='תמונה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.account', verbose_name='ספק')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
            },
        ),
    ]
